In [1]:
### Stats for batting scaped from baseball-reference.com ###

In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup, Comment

In [3]:
bat_stats_url = "https://www.baseball-reference.com/teams/PHI/batteam.shtml"

In [4]:
data_b = requests.get(bat_stats_url)

In [5]:
soup = BeautifulSoup(data_b.text)

In [6]:
bat_stats_table = soup.select('table.stats_table')[0]

In [7]:
bat_year_stats = pd.read_html(data_b.text, match = 'Year-by-Year Team Batting')

In [8]:
bat_year_stats[0]

,Year,Lg,W,L,Finish,R/G,G,PA,AB,R,...,BB,SO,BA,OBP,SLG,OPS,E,DP,Fld%,BatAge
0,2022,NL East,86,73,3,4.67,159,5974,5403,742,...,470,1324,0.255,0.318,0.424,0.742,69,123,0.988,28.2
1,2021,NL East,82,80,2,4.53,162,6089,5366,734,...,564,1402,0.240,0.318,0.408,0.726,94,142,0.984,29.1
2,2020,NL East,28,32,3,5.10,60,2223,1948,306,...,229,480,0.257,0.342,0.439,0.781,35,57,0.983,28.5
3,2019,NL East,81,81,4,4.78,162,6261,5571,774,...,562,1453,0.246,0.319,0.427,0.746,97,136,0.984,27.6
4,2018,NL East,80,82,3,4.18,162,6136,5424,677,...,582,1520,0.234,0.314,0.393,0.707,123,138,0.979,26.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,NL,75,48,2,7.04,128,5067,4630,901,...,385,346,0.274,0.337,0.389,0.726,471,76,0.912,26.0
136,1886,NL,71,43,4,5.22,119,4354,4072,621,...,282,516,0.240,0.289,0.327,0.616,393,46,0.921,25.5
137,1885,NL,56,54,3,4.62,111,4113,3893,513,...,220,401,0.229,0.270,0.302,0.572,447,66,0.905,24.7
138,1884,NL,39,73,6,4.86,113,4207,3998,549,...,209,512,0.234,0.272,0.301,0.573,536,67,0.888,25.1
139,1883,NL,17,81,8,4.41,99,3717,3576,437,...,141,355,0.240,0.269,0.320,0.589,639,62,0.858,26.5

In [9]:
bat = bat_year_stats[0]

In [10]:
bat.shape

(140, 27)

In [11]:
### Scraping batting table 2

### import requests
### import pandas as pd
### from bs4 import BeautifulSoup, Comment

soup = BeautifulSoup(requests.get('https://www.baseball-reference.com/teams/PHI/batteam.shtml').text)

bat_per_game = pd.read_html([x.extract() for x in soup.find_all(string=lambda text: isinstance(text, Comment)) if 'id="yby_team_bat_per_game"' in x][0])[0]

In [12]:
bat_per_game

,Year,Lg,W,L,Finish,G,PA,AB,R,H,...,CS,BB,SO,BA,OBP,SLG,OPS,E,DP,Fld%
0,2022,NL East,86,73,3,159,37.6,33.98,4.67,8.65,...,0.17,2.96,8.33,0.255,0.318,0.424,0.742,0.43,0.77,0.988
1,2021,NL East,82,80,2,162,37.6,33.12,4.53,7.95,...,0.12,3.48,8.65,0.240,0.318,0.408,0.726,0.58,0.88,0.984
2,2020,NL East,28,32,3,60,37.1,32.47,5.10,8.33,...,0.13,3.82,8.00,0.257,0.342,0.439,0.781,0.58,0.95,0.983
3,2019,NL East,81,81,4,162,38.6,34.39,4.78,8.45,...,0.11,3.47,8.97,0.246,0.319,0.427,0.746,0.60,0.84,0.984
4,2018,NL East,80,82,3,162,37.9,33.48,4.18,7.85,...,0.16,3.59,9.38,0.234,0.314,0.393,0.707,0.76,0.85,0.979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,NL,75,48,2,128,39.6,36.17,7.04,9.91,...,NaN,3.01,2.70,0.274,0.337,0.389,0.726,3.68,0.59,0.912
136,1886,NL,71,43,4,119,36.6,34.22,5.22,8.20,...,NaN,2.37,4.34,0.240,0.289,0.327,0.616,3.30,0.39,0.921
137,1885,NL,56,54,3,111,37.1,35.07,4.62,8.03,...,NaN,1.98,3.61,0.229,0.270,0.302,0.572,4.03,0.59,0.905
138,1884,NL,39,73,6,113,37.2,35.38,4.86,8.27,...,NaN,1.85,4.53,0.234,0.272,0.301,0.573,4.74,0.59,0.888
139,1883,NL,17,81,8,99,37.5,36.12,4.41,8.68,...,NaN,1.42,3.59,0.240,0.269,0.320,0.589,6.45,0.63,0.858

In [13]:
### Stats for pitching scaped from baseball-reference.com ###

In [14]:
pitch_stats_url = "https://www.baseball-reference.com/teams/PHI/pitchteam.shtml"

In [15]:
data_p = requests.get(pitch_stats_url)

In [16]:
soup = BeautifulSoup(data_p.text)

In [17]:
pitch_stats_table = soup.select('table.stats_table')[0]

In [18]:
pitch_year_stats = pd.read_html(data_p.text, match = 'Year-by-Year Team Pitching')

In [19]:
pitch = pitch_year_stats[0]

In [20]:
pitch

,Year,Lg,W,L,Finish,RA/G,ERA,G,CG,tSho,...,HR,BB,SO,WHIP,SO9,HR9,E,DP,Fld%,PAge
0,2022,NL East,86,73,3,4.23,3.96,159,3,14,...,146,457,1400,1.251,8.98,0.94,69,123,0.988,29.2
1,2021,NL East,82,80,2,4.60,4.39,162,5,12,...,200,509,1480,1.290,9.39,1.27,94,142,0.984,28.8
2,2020,NL East,28,32,3,5.18,5.14,60,3,5,...,80,185,532,1.479,9.63,1.45,35,57,0.983,29.1
3,2019,NL East,81,81,4,4.90,4.53,162,3,7,...,258,546,1392,1.374,8.62,1.60,97,136,0.984,28.4
4,2018,NL East,80,82,3,4.49,4.14,162,0,12,...,171,500,1465,1.291,9.12,1.06,123,138,0.979,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,NL,75,48,2,5.48,3.47,128,119,7,...,48,305,435,1.305,3.46,0.38,471,76,0.912,24.4
136,1886,NL,71,43,4,4.18,2.45,119,110,10,...,29,264,540,1.135,4.65,0.25,393,46,0.921,22.8
137,1885,NL,56,54,3,4.60,2.39,111,108,10,...,18,218,378,1.105,3.49,0.17,447,66,0.905,22.3
138,1884,NL,39,73,6,7.29,3.93,113,106,3,...,37,254,411,1.370,3.77,0.34,536,67,0.888,20.9
139,1883,NL,17,81,8,8.96,5.34,99,91,3,...,20,125,253,1.610,2.63,0.21,639,62,0.858,21.3

In [21]:
pitch.rename(columns = {'H' : 'H_A', 'R' : 'R_A', 'HR':'HR_A', 'BB':'BB_A', 'SO':'Ks'}, inplace = True)

In [22]:
### Scraping pitching table 2

### import requests
### import pandas as pd
### from bs4 import BeautifulSoup, Comment

soup = BeautifulSoup(requests.get('https://www.baseball-reference.com/teams/PHI/pitchteam.shtml').text)

pitch_per_game = pd.read_html([x.extract() for x in soup.find_all(string=lambda text: isinstance(text, Comment)) if 'id="yby_team_pitch_per_game"' in x][0])[0]

In [23]:
pitch_per_game

,Year,Lg,W,L,Finish,RA/G,ERA,G,CG,tSho,...,HR,BB,SO,WHIP,SO9,HR9,E,DP,Fld%,PAge
0,2022,NL East,86,73,3,4.23,3.96,159,0.02,0.09,...,0.92,2.87,8.81,1.251,8.98,0.94,0.43,0.77,0.988,29.2
1,2021,NL East,82,80,2,4.60,4.39,162,0.03,0.07,...,1.23,3.14,9.14,1.290,9.39,1.27,0.58,0.88,0.984,28.8
2,2020,NL East,28,32,3,5.18,5.14,60,0.05,0.08,...,1.33,3.08,8.87,1.479,9.63,1.45,0.58,0.95,0.983,29.1
3,2019,NL East,81,81,4,4.90,4.53,162,0.02,0.04,...,1.59,3.37,8.59,1.374,8.62,1.60,0.60,0.84,0.984,28.4
4,2018,NL East,80,82,3,4.49,4.14,162,0.00,0.07,...,1.06,3.09,9.04,1.291,9.12,1.06,0.76,0.85,0.979,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,NL,75,48,2,5.48,3.47,128,0.93,0.05,...,0.38,2.38,3.40,1.305,3.46,0.38,3.68,0.59,0.912,24.4
136,1886,NL,71,43,4,4.18,2.45,119,0.92,0.08,...,0.24,2.22,4.54,1.135,4.65,0.25,3.30,0.39,0.921,22.8
137,1885,NL,56,54,3,4.60,2.39,111,0.97,0.09,...,0.16,1.96,3.41,1.105,3.49,0.17,4.03,0.59,0.905,22.3
138,1884,NL,39,73,6,7.29,3.93,113,0.94,0.03,...,0.33,2.25,3.64,1.370,3.77,0.34,4.74,0.59,0.888,20.9
139,1883,NL,17,81,8,8.96,5.34,99,0.92,0.03,...,0.20,1.26,2.56,1.610,2.63,0.21,6.45,0.63,0.858,21.3

In [24]:
pitch_per_game.rename(columns = {'H' : 'H_A', 'R' : 'R_A', 'HR':'HR_A', 'BB':'BB_A', 'SO':'Ks'}, inplace = True)

In [25]:
pitch_per_game

,Year,Lg,W,L,Finish,RA/G,ERA,G,CG,tSho,...,HR_A,BB_A,Ks,WHIP,SO9,HR9,E,DP,Fld%,PAge
0,2022,NL East,86,73,3,4.23,3.96,159,0.02,0.09,...,0.92,2.87,8.81,1.251,8.98,0.94,0.43,0.77,0.988,29.2
1,2021,NL East,82,80,2,4.60,4.39,162,0.03,0.07,...,1.23,3.14,9.14,1.290,9.39,1.27,0.58,0.88,0.984,28.8
2,2020,NL East,28,32,3,5.18,5.14,60,0.05,0.08,...,1.33,3.08,8.87,1.479,9.63,1.45,0.58,0.95,0.983,29.1
3,2019,NL East,81,81,4,4.90,4.53,162,0.02,0.04,...,1.59,3.37,8.59,1.374,8.62,1.60,0.60,0.84,0.984,28.4
4,2018,NL East,80,82,3,4.49,4.14,162,0.00,0.07,...,1.06,3.09,9.04,1.291,9.12,1.06,0.76,0.85,0.979,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,NL,75,48,2,5.48,3.47,128,0.93,0.05,...,0.38,2.38,3.40,1.305,3.46,0.38,3.68,0.59,0.912,24.4
136,1886,NL,71,43,4,4.18,2.45,119,0.92,0.08,...,0.24,2.22,4.54,1.135,4.65,0.25,3.30,0.39,0.921,22.8
137,1885,NL,56,54,3,4.60,2.39,111,0.97,0.09,...,0.16,1.96,3.41,1.105,3.49,0.17,4.03,0.59,0.905,22.3
138,1884,NL,39,73,6,7.29,3.93,113,0.94,0.03,...,0.33,2.25,3.64,1.370,3.77,0.34,4.74,0.59,0.888,20.9
139,1883,NL,17,81,8,8.96,5.34,99,0.92,0.03,...,0.20,1.26,2.56,1.610,2.63,0.21,6.45,0.63,0.858,21.3

In [26]:
### Combinding two tables

In [27]:
pitch.columns.values.tolist()

['Year',
 'Lg',
 'W',
 'L',
 'Finish',
 'RA/G',
 'ERA',
 'G',
 'CG',
 'tSho',
 'SV',
 'IP',
 'H_A',
 'R_A',
 'ER',
 'HR_A',
 'BB_A',
 'Ks',
 'WHIP',
 'SO9',
 'HR9',
 'E',
 'DP',
 'Fld%',
 'PAge']

In [28]:
bat.columns.values.tolist()

['Year',
 'Lg',
 'W',
 'L',
 'Finish',
 'R/G',
 'G',
 'PA',
 'AB',
 'R',
 'H',
 '2B',
 '3B',
 'HR',
 'RBI',
 'SB',
 'CS',
 'BB',
 'SO',
 'BA',
 'OBP',
 'SLG',
 'OPS',
 'E',
 'DP',
 'Fld%',
 'BatAge']

In [29]:
team_data = bat.merge(pitch[['Year','RA/G','ERA','CG','tSho','SV','IP',
                              'H_A','R_A','ER','HR_A','BB_A','Ks','WHIP','SO9','HR9','PAge']],on='Year')

In [30]:
team_data.shape

(140, 43)

In [31]:
team_data.columns = [c.upper() for c in team_data.columns]

team_data = team_data.drop(labels=0, axis=0)

team_data = team_data.drop(columns="LG")

In [32]:
team_data

,YEAR,W,L,FINISH,R/G,G,PA,AB,R,H,...,H_A,R_A,ER,HR_A,BB_A,KS,WHIP,SO9,HR9,PAGE
1,2021,82,80,2,4.53,162,6089,5366,734,1288,...,1321,745,692,200,509,1480,1.290,9.39,1.27,28.8
2,2020,28,32,3,5.10,60,2223,1948,306,500,...,550,311,284,80,185,532,1.479,9.63,1.45,29.1
3,2019,81,81,4,4.78,162,6261,5571,774,1369,...,1452,794,731,258,546,1392,1.374,8.62,1.60,28.4
4,2018,80,82,3,4.18,162,6136,5424,677,1271,...,1366,728,665,171,500,1465,1.291,9.12,1.06,26.8
5,2017,66,96,5,4.26,162,6133,5535,690,1382,...,1471,782,729,221,527,1309,1.387,8.18,1.38,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1887,75,48,2,7.04,128,5067,4630,901,1269,...,1173,702,437,48,305,435,1.305,3.46,0.38,24.4
136,1886,71,43,4,5.22,119,4354,4072,621,976,...,923,498,285,29,264,540,1.135,4.65,0.25,22.8
137,1885,56,54,3,4.62,111,4113,3893,513,891,...,860,511,259,18,218,378,1.105,3.49,0.17,22.3
138,1884,39,73,6,4.86,113,4207,3998,549,934,...,1090,824,428,37,254,411,1.370,3.77,0.34,20.9
139,1883,17,81,8,4.41,99,3717,3576,437,859,...,1267,887,513,20,125,253,1.610,2.63,0.21,21.3

In [33]:
team_name = bat_stats_url.split("/")[-2]

In [34]:
team_name

'PHI'

In [35]:
team_data.insert(0, 'TEAM', team_name)

In [36]:
team_data

,TEAM,YEAR,W,L,FINISH,R/G,G,PA,AB,R,...,H_A,R_A,ER,HR_A,BB_A,KS,WHIP,SO9,HR9,PAGE
1,PHI,2021,82,80,2,4.53,162,6089,5366,734,...,1321,745,692,200,509,1480,1.290,9.39,1.27,28.8
2,PHI,2020,28,32,3,5.10,60,2223,1948,306,...,550,311,284,80,185,532,1.479,9.63,1.45,29.1
3,PHI,2019,81,81,4,4.78,162,6261,5571,774,...,1452,794,731,258,546,1392,1.374,8.62,1.60,28.4
4,PHI,2018,80,82,3,4.18,162,6136,5424,677,...,1366,728,665,171,500,1465,1.291,9.12,1.06,26.8
5,PHI,2017,66,96,5,4.26,162,6133,5535,690,...,1471,782,729,221,527,1309,1.387,8.18,1.38,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,PHI,1887,75,48,2,7.04,128,5067,4630,901,...,1173,702,437,48,305,435,1.305,3.46,0.38,24.4
136,PHI,1886,71,43,4,5.22,119,4354,4072,621,...,923,498,285,29,264,540,1.135,4.65,0.25,22.8
137,PHI,1885,56,54,3,4.62,111,4113,3893,513,...,860,511,259,18,218,378,1.105,3.49,0.17,22.3
138,PHI,1884,39,73,6,4.86,113,4207,3998,549,...,1090,824,428,37,254,411,1.370,3.77,0.34,20.9
139,PHI,1883,17,81,8,4.41,99,3717,3576,437,...,1267,887,513,20,125,253,1.610,2.63,0.21,21.3

In [37]:
### Combined 2 per game tables

team_per_game = bat_per_game.merge(pitch_per_game[['Year','RA/G','ERA','CG','tSho','SV','IP',
                              'H_A','R_A','ER','HR_A','BB_A','Ks','WHIP','SO9','HR9','PAge']],on='Year')

In [38]:
team_per_game.columns = [c.upper() for c in team_per_game.columns]

team_per_game = team_per_game.drop(labels=0, axis=0)

team_per_game = team_per_game.drop(columns="LG")

team_per_game.insert(0, 'TEAM', team_name)

In [39]:
team_per_game

,TEAM,YEAR,W,L,FINISH,G,PA,AB,R,H,...,H_A,R_A,ER,HR_A,BB_A,KS,WHIP,SO9,HR9,PAGE
1,PHI,2021,82,80,2,162,37.6,33.12,4.53,7.95,...,8.15,4.60,4.27,1.23,3.14,9.14,1.290,9.39,1.27,28.8
2,PHI,2020,28,32,3,60,37.1,32.47,5.10,8.33,...,9.17,5.18,4.73,1.33,3.08,8.87,1.479,9.63,1.45,29.1
3,PHI,2019,81,81,4,162,38.6,34.39,4.78,8.45,...,8.96,4.90,4.51,1.59,3.37,8.59,1.374,8.62,1.60,28.4
4,PHI,2018,80,82,3,162,37.9,33.48,4.18,7.85,...,8.43,4.49,4.10,1.06,3.09,9.04,1.291,9.12,1.06,26.8
5,PHI,2017,66,96,5,162,37.9,34.17,4.26,8.53,...,9.08,4.83,4.50,1.36,3.25,8.08,1.387,8.18,1.38,26.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,PHI,1887,75,48,2,128,39.6,36.17,7.04,9.91,...,9.16,5.48,3.41,0.38,2.38,3.40,1.305,3.46,0.38,24.4
136,PHI,1886,71,43,4,119,36.6,34.22,5.22,8.20,...,7.76,4.18,2.39,0.24,2.22,4.54,1.135,4.65,0.25,22.8
137,PHI,1885,56,54,3,111,37.1,35.07,4.62,8.03,...,7.75,4.60,2.33,0.16,1.96,3.41,1.105,3.49,0.17,22.3
138,PHI,1884,39,73,6,113,37.2,35.38,4.86,8.27,...,9.65,7.29,3.79,0.33,2.25,3.64,1.370,3.77,0.34,20.9
139,PHI,1883,17,81,8,99,37.5,36.12,4.41,8.68,...,12.80,8.96,5.18,0.20,1.26,2.56,1.610,2.63,0.21,21.3

In [40]:
phillies_stats = team_data

per_game_phillies = team_per_game

In [41]:
phillies_stats.to_csv("phillies_stats.csv")

per_game_phillies.to_csv('per_game_phillies')